### ISSUE TITLE
Not working with Arduino 1.0.1-7 / gcc-avr 4.7.0-2 amd64

### ISSUE THREAD

**Issue by malexmave** [logicalzero/gamby#3]
Hi,

I'm using Arduino 1.0.1-7 with gcc-avr 4.7.0-2 (On Linux Mint 14 x64), and the libraries don't work for me. When I try to compile the FirstTest, I get:

`In file included from FirstTest.cpp:12:0:
/home/username/sketchbook/libraries/Gamby/Gamby.h:229:23: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:229:34: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:230:23: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:230:34: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:258:9: error: ‘prog_int32_t’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:310:9: error: ‘prog_uint16_t’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:337:37: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:337:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:338:37: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:338:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:338:57: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:338:68: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:339:37: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:339:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:340:37: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:340:48: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
/home/username/sketchbook/libraries/Gamby/Gamby.h:340:63: error: ‘prog_uchar’ does not name a type
/home/username/sketchbook/libraries/Gamby/Gamby.h:340:74: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
FirstTest.cpp:22:9: error: ‘prog_uchar’ does not name a type
FirstTest.cpp:36:9: error: ‘prog_uchar’ does not name a type
FirstTest.cpp:49:9: error: ‘prog_uchar’ does not name a type
FirstTest.cpp:62:9: error: ‘prog_uchar’ does not name a type
FirstTest.cpp:75:9: error: ‘prog_uchar’ does not name a type
FirstTest.cpp: In function ‘void setup()’:
FirstTest.cpp:98:18: error: ‘screen_logo_graphic_1’ was not declared in this scope
FirstTest.cpp:100:18: error: ‘screen_logo_graphic_2’ was not declared in this scope
FirstTest.cpp:102:18: error: ‘screen_logo_graphic_3’ was not declared in this scope
FirstTest.cpp:104:18: error: ‘screen_logo_graphic_4’ was not declared in this scope
FirstTest.cpp:106:18: error: ‘screen_logo_text’ was not declared in this scope`

Appearently, [`prog_*` is deprecated](http://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html#gaa475b6b81fd8b34de45695da1da523b6). It looks like those variables now have to be declared as `PROGMEM const [vartype] [varname]`.

I'll be checking the code and see if I can fix it, but I just wanted to let you know.

malexmave
